FROM node:slim 
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG JWT_SECRET_KEY
ARG DATABASE_URL
ARG PORT
ARG REDIRECT_URL
ARG BACKEND_URL
ARG FRONTEND_URL
ARG BUCKET_NAME
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV PORT ${PORT}
ENV FRONTEND_URL ${FRONTEND_URL}
ENV BACKEND_URL ${BACKEND_URL}
ENV REDIRECT_URL ${REDIRECT_URL}
ENV CLIENT_ID ${CLIENT_ID}
ENV CLIENT_SECRET ${CLIENT_SECRET}
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}
ENV DATABASE_URL ${DATABASE_URL}
ENV PORT ${PORT}
ENV REDIRECT_URL ${REDIRECT_URL}
ENV BACKEND_URL ${BACKEND_URL}
ENV FRONTEND_URL ${FRONTEND_URL}
ENV BUCKET_NAME ${BUCKET_NAME}
ENV AWS_REGION ${AWS_REGION}
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
EXPOSE ${PORT}
CMD ["npm","start"]
