version: '3.8'
services:
  frontend:
    image: vijayvenkatj/campusconnect-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"    
  backend:
    image: vijayvenkatj/campusconnect-backend-dev:latest
    restart: always
    ports:
      - "5000:5000"
