name: Build and Push Multi-Architecture Docker Image

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: vijayvenkatj/campusconnect-backend:latest
          build-args: |
            PORT=${{ secrets.PORT }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            REDIRECT_URL=${{ secrets.REDIRECT_URL }}
            CLIENT_ID=${{ secrets.CLIENT_ID }}
            CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
